// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxb-BMAGZxaTrEKe5JL3HeYh-c4GpbWA',
    appId: '1:645741691834:web:744fb02625e32ef22cd383',
    messagingSenderId: '645741691834',
    projectId: 'dictionaryapp-f9f77',
    authDomain: 'dictionaryapp-f9f77.firebaseapp.com',
    storageBucket: 'dictionaryapp-f9f77.appspot.com',
    measurementId: 'G-16Z28EJ5D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFo1x_3Vc3m9XhuCK-cRh6PmjZCEmTmw',
    appId: '1:645741691834:android:23fb7fa6ae660a0e2cd383',
    messagingSenderId: '645741691834',
    projectId: 'dictionaryapp-f9f77',
    storageBucket: 'dictionaryapp-f9f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ_8uYhopvtX2EA3_00i5wexnj0SX8z2M',
    appId: '1:645741691834:ios:6d87c7303cdd35df2cd383',
    messagingSenderId: '645741691834',
    projectId: 'dictionaryapp-f9f77',
    storageBucket: 'dictionaryapp-f9f77.appspot.com',
    iosBundleId: 'com.example.dictionaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ_8uYhopvtX2EA3_00i5wexnj0SX8z2M',
    appId: '1:645741691834:ios:9e12f1e53efa1d792cd383',
    messagingSenderId: '645741691834',
    projectId: 'dictionaryapp-f9f77',
    storageBucket: 'dictionaryapp-f9f77.appspot.com',
    iosBundleId: 'com.example.dictionaryapp.RunnerTests',
  );
}
